### PR TITLE
fix mermaid + change in description + new plot importance feature function + fix bug in CV function + add 1 Vignette

### PR DESCRIPTION
**Pull request by pommedeterresautee**
https://github.com/tqchen/xgboost/issues/154

### CODE REVIEW

**Comment by hetong007** [comment]
It seems `make Rpack` returns this error message:

```
* checking package dependencies ... ERROR
Package required but not available: ‘Ckmeans.1d.dp’
```

Do you mind to fix it?

**Comment by pommedeterresautee** [comment]
That's strange http://cran.r-project.org/web/packages/Ckmeans.1d.dp/index.html exists!

Will test tomorrow, I have no access to a computer right now.

**Comment by pommedeterresautee** [comment]
(may I should add a version number to the requirements)

**Comment by pommedeterresautee** [comment]
Just tested on Linux make Rpack. No error message. Then I removed from my computer the Ckmeans package and got the same error than you.

Therefore I think it's a false error message. To have real issue you need to install xgboost (with its dependencies) one time first so everything required is installed then launch make Rpack. 

However I have added more updated version of some packages so everything is up to date.

**Comment by pommedeterresautee** [comment]
@hetong007 just tried with other requirements, same issue.

**Comment by hetong007** [comment]
It's smooth now. Blame me for misunderstood the mechanism of `R CMD check`. It will not install the missing dependencies, unlike what usually happens in the installation step.

**Pull request merged**
