### PR TITLE
Sync xgboost R function documentation with Wiki one (add all parameters)

### PR DESCRIPTION
**Pull request by pommedeterresautee**

### CODE REVIEW

**Comment by tqchen** [comment]
Let us keep all the parameters in the wiki for now, and use the old documentation style. There are two reasons: (1) make things easy to document as we add new things (2) most parameters in the parameter section can be confusing for R users, the old documentation style only mentioned the key features, makes things easier for new user

**Comment by pommedeterresautee** [comment]
I fully understand your two points. I added the documentation to address a critic a colleague told me when I show her the package, she didn't understood why most of the feature where missing the package (she thought that some of them were Python only feature). And there was this guy putting a comment under one commit in this repository (I don't find the link any more unfortunately) saying the documentation of the package was to improve and he was supposed to tell us his success and failures with the package and provide us with some useful critics, something like this... 

Regarding your points:
- making our lives easier seems not relevant from a user package point of view. It is to the people taking care of the package to update things (and I am Ok to keep it updated, I am going to implement the package in our production process at work, therefore I won't flew away soon :-) )
- some parameters may confuse R package users : I fully agree on that point. Fortunately for us, there is a detail section in any function documentation. Right now it is not used a lot. I can move advanced stuffs in detail function.

The goal is to have a documentation which is both at the same time complete and easy to use. 
In this first shot I just copy paste clean the documentation. It is a first step we can work on. 

Last thought, I was thinking that Wiki and R documentation should be identical (in particular same organisation). I changed my mind. From what I see in R meetup in Paris (not the same that ML meetup), I don't think average R users have deep machine learning culture like python one. It's probably because there are less ML tools. I think now that having a documentation better targeted for this average R user makes sense.

Sorry for this long post, I am lawyer and tend to love writing a lot :-)

**Comment by pommedeterresautee** [comment]
I think the following things should go to detail part:
- nthread: automatically detected
- num_pbuffer: automatically detected
- num_feature: automatically detected
- eval_metric (and all metrics): automatically detected regarding objective
- map: too complex
- ndcg@n ... : too complex
- seed: too specific (need to reproduce computation)

The most important thing I would want to find as a user in the documentation of this function are the objectives (without that information the purpose of xgboost is missing of the R documentation) and the most important specific parameters of trees and linear learning.

**Comment by tqchen** [comment]
Good, I agree that the training parameters of tree and linear learning should go into the documentation. Let us leave the rest of detailed things in wiki, and target the average R user to present only the relevant parameters.

* seed is no longer needed and replaced by R's seed function
* automatically detected things are

**Pull request closed without merging**
