### PR TITLE
[python] Fixed the dll import for relative paths + various cleanup.

### PR DESCRIPTION
**Pull request by aldanor**
- DLL import now works when `__file__` is a relative path
- Various PEP8 and whitespace fixes + whitespace cleanup
- Docstring fixes (conform to numpydoc)
- Added `__all__` to the module
- Fixed mutable default values
- Removed print statements
- py2/py3-compatible string-type checks
- Replace asserts with proper exceptions
- Make classes new-style (derive from `object`)

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for the PR! It is now merged into master

**Comment by aldanor** [comment]
Thanks for merging fast!

I was thinking of converting this to a proper clean Python package (so you just run `setup.py` and that builds a proper Python C extension automatically, no more loading dlls manually, no more manual path hacks) and maybe refactoring the API slightly along the way so it's more Pythonic; this would also allow you to publish the package to `pypi` as a binary wheel if you ever wanted to. What do you think? (I would have to do it in a private fork for work-related reasons regardless; but if you don't mind some changes I could open an upstream pull request here)

// there are no unit tests though which is quite sad and makes the whole endeavour bit more complicated than it should be

**Comment by tqchen** [comment]
It would be great if you could help doing that! 
For unit test-cases, the examples in https://github.com/tqchen/xgboost/tree/master/demo/guide-python might could been reused

**Comment by tqchen** [comment]
I think it would be nice if we could make xgboost.py work in both the manual mode and using setup.py 
The current one could be inconvenient for installations, but could be used for fast adaptation and testing of new codes in c sides.

If you like, we can open an issue on the possible improvement on python package

**Comment by aldanor** [comment]
Hmm; there are many packages that do that and still allow rapid development. For one thing, you can always do a
```sh
python setup.py build_ext --inplace
``` 
and that would just rebuild the package inplace and put the `.so` file(s) next to their sources. Exactly the same as it is currently done, but cleaner because you're using the same setup logic.

The wrapper could also be written in Cython which would let you avoid the whole ctypes mess in the pure-Python part :)

**Comment by aldanor** [comment]
https://github.com/jaraco/setuptools/blob/master/setuptools/command/build_ext.py#L46

**Comment by tqchen** [comment]
I see, I guess it was not hard to support both in python anyway. Since it is only about the relative position of the shared library.

**Comment by aldanor** [comment]
Yep; you would be able to rebuild the whole thing with `build_ext --inplace` and reload it in your Python terminal instantly if you wanted to. Or install it properly into a virtual environment and test things there in an isolated way (a much preferred method generally).

Ok, this will sure require some work so I'll get back to you when something's ready!

**Pull request merged**
